# Generated by Django 2.1 on 2018-08-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='university',
            new_name='university_id',
        ),
    ]
